# Generated by Django 2.0 on 2018-01-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('macro_protein', models.IntegerField()),
                ('macro_carb', models.IntegerField()),
                ('macro_fat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.Diet')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('reddit_link', models.URLField()),
                ('user', models.CharField(max_length=200)),
                ('user_age', models.CharField(max_length=100)),
                ('user_sex', models.CharField(max_length=20)),
                ('user_height', models.IntegerField()),
                ('user_body_type_start', models.CharField(max_length=200)),
                ('user_body_type_end', models.CharField(max_length=200)),
                ('user_starting_weight', models.IntegerField()),
                ('user_ending_weight', models.IntegerField()),
                ('goals', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.Plan'),
        ),
    ]
