# Generated by Django 2.0 on 2018-01-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
